// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiBkyXGS6JkyF3ic0Yr732S9ghjH5n654',
    appId: '1:956624354008:web:7afdd393428d19cc8775ad',
    messagingSenderId: '956624354008',
    projectId: 'spotifyclone-cabd1',
    authDomain: 'spotifyclone-cabd1.firebaseapp.com',
    storageBucket: 'spotifyclone-cabd1.appspot.com',
    measurementId: 'G-5ZH5MRTNK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaxZ5ynek_jyT3AtWrqlmzIil5JE-bois',
    appId: '1:956624354008:android:b81b596fa099afee8775ad',
    messagingSenderId: '956624354008',
    projectId: 'spotifyclone-cabd1',
    storageBucket: 'spotifyclone-cabd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgM-bVnFpt4UMTQOOKY41x0rnX91mz1JA',
    appId: '1:956624354008:ios:7595462bbbb2b1518775ad',
    messagingSenderId: '956624354008',
    projectId: 'spotifyclone-cabd1',
    storageBucket: 'spotifyclone-cabd1.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiBkyXGS6JkyF3ic0Yr732S9ghjH5n654',
    appId: '1:956624354008:web:6a04227570591b258775ad',
    messagingSenderId: '956624354008',
    projectId: 'spotifyclone-cabd1',
    authDomain: 'spotifyclone-cabd1.firebaseapp.com',
    storageBucket: 'spotifyclone-cabd1.appspot.com',
    measurementId: 'G-VC11KWLJ31',
  );
}
